UPDATE "commentary" SET "match_id" = 0 WHERE "match_id" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "match_id" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "minute" = 0 WHERE "minute" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "minute" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "sequence" = 0 WHERE "sequence" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "sequence" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "period" = '' WHERE "period" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "period" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "event_type" = '' WHERE "event_type" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "event_type" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "actor" = '' WHERE "actor" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "actor" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "team" = '' WHERE "team" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "team" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "message" = '' WHERE "message" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "message" SET NOT NULL;--> statement-breakpoint
UPDATE "commentary" SET "created_at" = NOW() WHERE "created_at" IS NULL;
ALTER TABLE "commentary" ALTER COLUMN "created_at" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "sport" = '' WHERE "sport" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "sport" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "home_team" = '' WHERE "home_team" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "home_team" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "away_team" = '' WHERE "away_team" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "away_team" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "status" = 'scheduled' WHERE "status" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "status" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "start_time" = NOW() WHERE "start_time" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "start_time" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "home_score" = 0 WHERE "home_score" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "home_score" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "away_score" = 0 WHERE "away_score" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "away_score" SET NOT NULL;--> statement-breakpoint
UPDATE "matches" SET "created_at" = NOW() WHERE "created_at" IS NULL;
ALTER TABLE "matches" ALTER COLUMN "created_at" SET NOT NULL;